from fastapi import APIRouter
from fastapi.responses import FileResponse, RedirectResponse
import os
import tempfile
from database import get_db
from config import settings
from models import InspectionSession
from docx import Document
from services.pipeline_output_store import load_stage_output
from repositories.job_repository import job_repository

router = APIRouter()

@router.get("/videos/{inspection_id}")
async def download_video(inspection_id: str):
    job = await job_repository.get_job(inspection_id)
    if not job or not job.get("video_path"):
        return {"error": "Video not found"}
        
    video_path = job["video_path"]
    if not os.path.exists(video_path):
        return {"error": "Video file missing on disk"}
        
    return FileResponse(video_path, media_type="video/mp4")


async def _build_dummy_batch_report(batch_id: str, sessions: list[InspectionSession], repair_payloads: list[dict]) -> str:
    document = Document()
    document.add_heading("Combined Vessel Inspection Report", level=0)
    document.add_paragraph("Generated by the dummy report-generation microservice.")
    document.add_paragraph(f"Batch ID: {batch_id}")
    document.add_paragraph(f"Session Count: {len(sessions)}")

    total_cost = 0.0
    total_defects = 0
    defect_rows = []

    for payload in repair_payloads:
        summary = payload.get("repair_summary", {})
        total_cost += float(summary.get("total_estimated_cost", 0) or 0)
        total_defects += int(summary.get("total_defects", 0) or 0)
        for defect_id, defect in (payload.get("defect_repairs") or {}).items():
            defect_rows.append(
                (
                    defect_id,
                    defect.get("severity"),
                    defect.get("defect_metadata", {}).get("best_frame"),
                    defect.get("repair_estimation", {}).get("estimated_total_cost", 0),
                )
            )

    document.add_paragraph(f"Total Defects: {total_defects}")
    document.add_paragraph(f"Estimated Cost: INR {total_cost:,.2f}")

    if defect_rows:
        table = document.add_table(rows=1, cols=4)
        for cell, header in zip(table.rows[0].cells, ["Defect ID", "Severity", "Best Frame", "Estimated Cost"]):
            cell.text = header
        for defect_id, severity, best_frame, estimated_cost in defect_rows:
            row = table.add_row().cells
            row[0].text = str(defect_id)
            row[1].text = str(severity)
            row[2].text = str(best_frame)
            row[3].text = f"INR {float(estimated_cost):,.2f}"

    import io
    output_dir = os.path.join(settings.output_folder, "batch_reports")
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, f"combined_batch_{batch_id}.docx")
    
    document.save(file_path)
    return file_path

@router.get("/download/{session_id}")
async def download_report(session_id: str):
    db = get_db()
    session = await db.inspection_sessions.find_one({"session_id": session_id})

    if not session:
        return {"error": "Session not found"}

    doc_path = session.get("document_path")
    if not doc_path:
        return {"error": "Document not ready"}
    if not os.path.exists(doc_path):
        return {"error": "Document file missing on disk"}
        
    return FileResponse(doc_path)

@router.get("/download/{session_id}/pdf")
async def download_report_pdf(session_id: str):
    db = get_db()
    session = await db.inspection_sessions.find_one({"session_id": session_id})

    if not session:
        return {"error": "Session not found"}

    docx_url = session.get("document_path")
    if not docx_url:
        return {"error": "Document not ready"}
    if not os.path.exists(docx_url):
        return {"error": "Document file missing on disk"}

    pdf_path = docx_url.replace(".docx", ".pdf")
    
    if not os.path.exists(pdf_path):
        try:
            import pythoncom
            pythoncom.CoInitialize()
            try:
                from docx2pdf import convert
                convert(docx_url, pdf_path)
            finally:
                pythoncom.CoUninitialize()
        except Exception as e:
            return {"error": f"Failed to generate PDF: {e}"}

    if not os.path.exists(pdf_path):
        return {"error": "Failed to generate PDF"}
        
    return FileResponse(pdf_path, media_type="application/pdf")

@router.get("/batches/{batch_id}/download/docx")
async def download_batch_report(batch_id: str):
    db = get_db()
    docs = await db.inspection_sessions.find({"batch_id": batch_id}).sort("created_at", 1).to_list(length=None)
    
    if not docs:
        analysis_docs = await db.analysis_sessions.find({"visit_id": batch_id}).to_list(length=None)
        if analysis_docs:
            session_ids = [doc.get("session_id") for doc in analysis_docs if doc.get("session_id")]
            docs = await db.inspection_sessions.find({"session_id": {"$in": session_ids}}).sort("created_at", 1).to_list(length=None)

    if not docs:
        return {"error": "Batch not found"}

    sessions = [InspectionSession(**doc) for doc in docs]
    
    file_id = None
    # We should cache batch_file_id in db, but to keep it simple we generate it on the fly
    imo_number = sessions[0].imo_number
    if imo_number:
        all_vessel_docs = await db.inspection_sessions.find({"imo_number": imo_number}).sort("created_at", 1).to_list(length=None)
        all_sessions = [InspectionSession(**doc) for doc in all_vessel_docs]
    else:
        all_sessions = sessions

    repair_payloads = []
    for session in all_sessions:
        payload = load_stage_output(session.session_id, "repair_estimation")
        if payload:
            repair_payloads.append(payload)
    file_path = await _build_dummy_batch_report(batch_id, all_sessions, repair_payloads)
    
    if not file_path or not os.path.exists(file_path):
         return {"error": "Failed to generate report"}

    return FileResponse(file_path)

@router.get("/batches/{batch_id}/download/pdf")
async def download_batch_report_pdf(batch_id: str):
    db = get_db()
    docs = await db.inspection_sessions.find({"batch_id": batch_id}).sort("created_at", 1).to_list(length=None)
    
    if not docs:
        analysis_docs = await db.analysis_sessions.find({"visit_id": batch_id}).to_list(length=None)
        if analysis_docs:
            session_ids = [doc.get("session_id") for doc in analysis_docs if doc.get("session_id")]
            docs = await db.inspection_sessions.find({"session_id": {"$in": session_ids}}).sort("created_at", 1).to_list(length=None)

    if not docs:
        return {"error": "Batch not found"}

    sessions = [InspectionSession(**doc) for doc in docs]
    
    file_id = None
    imo_number = sessions[0].imo_number
    if imo_number:
        # Fetch ALL sessions for this vessel to include in the report
        all_vessel_docs = await db.inspection_sessions.find({"imo_number": imo_number}).sort("created_at", 1).to_list(length=None)
        all_sessions = [InspectionSession(**doc) for doc in all_vessel_docs]
    else:
        all_sessions = sessions

    repair_payloads = []
    for session in all_sessions:
        payload = load_stage_output(session.session_id, "repair_estimation")
        if payload:
            repair_payloads.append(payload)
    
    file_path = await _build_dummy_batch_report(batch_id, all_sessions, repair_payloads)
        
    if not file_path or not os.path.exists(file_path):
         return {"error": "Failed to generate report"}

    pdf_path = file_path.replace(".docx", ".pdf")
    
    if not os.path.exists(pdf_path):
        try:
            import pythoncom
            pythoncom.CoInitialize()
            try:
                from docx2pdf import convert
                convert(file_path, pdf_path)
            finally:
                pythoncom.CoUninitialize()
        except Exception as e:
            return {"error": f"Failed to generate PDF: {e}"}

    if not os.path.exists(pdf_path):
        return {"error": "Failed to generate PDF"}

    return FileResponse(pdf_path, media_type="application/pdf")
